### PR TITLE
Add Docker container, instructions, and modified server to accommodate.

### PR DESCRIPTION
**Pull request by l50**
Hey, 

Big fan of your work, hopefully this is a useful contribution.

### CODE REVIEW

**Comment by averagesecurityguy** [comment]
Thank you for your kind words and for the pull request.

**Comment by averagesecurityguy** [comment]
I made a couple of changes to ensure the server defaults to 127.0.0.1 since I don't have TLS configured yet. Please let me know if this breaks the docker build.

**Comment by l50** [comment]
It did, but I fixed it. New PR coming in.

**Comment by averagesecurityguy** [comment]
Thanks. Pull the latest version. I should have it fixed now.

**Pull request merged**
